# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Test

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and test (Node ${{ matrix.node.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - { name: Current,      version: current }
          - { name: LTS,          version: lts/* }
          - { name: Previous LTS, version: lts/-1 }
    steps:
      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@master
        with:
          node-version: ${{ matrix.node.version }}
